learning_users/basic_app/urls.py
from django.urls import path
from basic_app import views

# Template URLS

app_name = 'basic_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login', views.user_login, name='user_login')
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from basic_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('special/',views.special, name='special')
]

learning_users/basic_app/models.py
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    #Additonal 
    portfolio_site = models.URLField(blank=True)
    
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    
    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    
    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm

# importing for login
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')

#The decorator login_required will guarantee that only a user that is logged in can logout
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse('You are logged in, Nice!')


def register(request):
    
    # Depend on this variable to check if someone is registered or not
    registered = False
    
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            
            # Set the user_form data to the variable form and save it directly to the database
            user = user_form.save()
            # Hashes the user's password by using the set_password method that goes to the settings.py file 
            # and set it as the hash and then, saves it to the database
            user.set_password(user.password)
            user.save()
            
            # We set the profile_form data to the profile variabe but we set commit=False
            # so we can manipulate the data before saving to avoid collision errors
            profile = profile_form.save(commit=False)
            
            # Sets up the one to one relationship as we did in models
            # We are linking three files (views.py, forms.py and models.py)
            # We need to do it to add the extras to the profile
            profile.user = user
            
            
            # If we want to upload any file (pic, cv, pdf etc) we will use request.FILES
            if 'profile_pic' in request.FILES:
                # Set the attribute profile_pic to the request.FILES that acts like a dictionary and we will pass 
                # What we created in the models for this attribute.
                profile.profile_pic = request.FILES['profile_pic']
                
            profile.save()
            
            registered = True
        
        else:
            print(user_form.errors, profile_form.errors)
    
    else:
        # If the request was an HTTP request we will pass the instance of the forms
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    
    # returning everything to the page
    return render(request, 'basic_app/registration.html',
                                    {'user_form': user_form,
                                     'profile_form':profile_form,
                                     'registered': registered})
    

# Creating the view for the login page
def user_login(request):
    if request.method == 'POST':
        # Grabbing the information from the HTML using the name passed there
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        # Authenticating the user and password using the imported authenticate
        user = authenticate(username=username, password=password)
        
        # If the user was authenticated
        if user:
            # Checking if the account is active
            if user.is_active:
                # Log the user in
                login(request, user)
                # Send the user back to index page 
                return HttpResponseRedirect(reverse('index'))
            
            else:
                return HttpResponse("Account not active")
        
        else:
            print("Someone tried to login and failed!")
            print(f"Username:{username} and Password:{password}")
            return HttpResponse("Invalid Login details supplied!")
    else:
        return render(request,'basic_app/login.html', {})

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="navbar-link" href="{% url 'basic_app:register' %}">Registration</a></li>
                <!--If the user was authenticated, we will display the logout link-->
                {% if user.is_authenticated %}
                <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li><a class="navbar-link" href="{% url 'basic_app:user_login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
    
</body>
</html>

learning_users/templates/basic_app/index.html
{% extends 'basic_app/base.html' %}

{% block body_block %}

<div class="jumbotron">
    <h1>Django Level Five</h1>
</div>

{% endblock %}

learning_users/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}

{% block body_block %}

<div class='jumbotron'>

    <h1>Please Login</h1>

    <form action="{% url 'basic_app:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password">
        
        <input type="submit" name="" value="Login">

    </form>

</div>

{% endblock %}

learning_users/templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% load static %}

{% block body_block %}

<div class="jumbotron">

    {% if registered %}
        <h1>Thank You for registering!</h1>
    {% else %}
        <h1>Register here!</h1>
        <h3>Fill out the form:</h3>

        <!--Since we are using multimedia data that we're uploading such as the image file
             for this project, we need the enctype="multipart/form-data otherwise", image
             uploading won't work!-->
        <form enctype="multipart/form-data" method="post" >
            {% csrf_token %}
            <!--Will grab the information from our form and will pass it as a paragraph to html-->
            {{ user_form.as_p }}
            {{ profile_form.as_p}}

            <input type="submit" name="" value="Register">
        </form> 
    {% endif %}

</div>

{% endblock  %}